# Generated by Django 4.1.7 on 2024-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English_word',
            fields=[
                ('eng_word', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='英単語ワード')),
                ('eng_word_mean', models.CharField(max_length=30, verbose_name='英単語の意味')),
                ('eng_part_of_speech', models.CharField(max_length=10, verbose_name='品詞')),
                ('eng_level', models.CharField(max_length=2, verbose_name='英単語レベル')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='利用者ID')),
                ('password', models.CharField(max_length=15, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Users_answer_data',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='利用者ID')),
                ('log_id', models.CharField(max_length=3, verbose_name='ログID')),
                ('eng_word', models.CharField(max_length=30, verbose_name='英単語ワード')),
            ],
        ),
    ]
