# Generated by Django 4.1.7 on 2024-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_answer_data',
            name='log_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ログID'),
        ),
        migrations.AlterField(
            model_name='users_answer_data',
            name='user_id',
            field=models.CharField(max_length=10, verbose_name='利用者ID'),
        ),
    ]
