# Generated by Django 4.1.7 on 2024-04-25 05:09

import api_sys.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0002_alter_users_answer_data_log_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('access_datetime', models.DateTimeField(default=api_sys.models.in_30_days)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_sys.user')),
            ],
        ),
    ]
