# Generated by Django 4.1.7 on 2024-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0003_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_answer_data',
            name='log_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ログID'),
        ),
    ]
