# Generated by Django 4.1.7 on 2024-04-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0004_alter_users_answer_data_log_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=30, verbose_name='英単語ワード')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_sys.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Users_answer_data',
        ),
    ]
