# Generated by Django 4.1.7 on 2024-05-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0005_answer_data_delete_users_answer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_sys.user', verbose_name='停止ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Miss',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_sys.user', verbose_name='試行ユーザー')),
                ('num', models.CharField(max_length=2, verbose_name='試行回数')),
            ],
        ),
    ]
