# Generated by Django 4.1.7 on 2024-05-02 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sys', '0006_lock_miss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_sys.user', verbose_name='停止ユーザー'),
        ),
        migrations.AlterField(
            model_name='miss',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_sys.user', verbose_name='試行ユーザー'),
        ),
    ]
